version: "3.1"

services:
  db:
    image: "postgres:${Tag}"
    restart: always
    env_file:
      - ./.env
    ports:
      - 5431:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
